// flow-typed signature: 1becce44f344e7ddc91c138bd08004b8
// flow-typed version: <<STUB>>/@flux-coordinator/heatmapjs_v^2.1.4/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@flux-coordinator/heatmapjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@flux-coordinator/heatmapjs" {
	declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@flux-coordinator/heatmapjs/build/heatmap" {
	declare module.exports: any;
}

declare module "@flux-coordinator/heatmapjs/build/heatmap.min" {
	declare module.exports: any;
}

declare module "@flux-coordinator/heatmapjs/docs/assets/js/prism" {
	declare module.exports: any;
}

declare module "@flux-coordinator/heatmapjs/plugins/angular-heatmap/angular-heatmap" {
	declare module.exports: any;
}

declare module "@flux-coordinator/heatmapjs/plugins/boilerplate" {
	declare module.exports: any;
}

declare module "@flux-coordinator/heatmapjs/plugins/gmaps-heatmap/gmaps-heatmap" {
	declare module.exports: any;
}

declare module "@flux-coordinator/heatmapjs/plugins/leaflet-heatmap/leaflet-heatmap" {
	declare module.exports: any;
}

declare module "@flux-coordinator/heatmapjs/plugins/segment-heatmap" {
	declare module.exports: any;
}

declare module "@flux-coordinator/heatmapjs/plugins/svg-area-heatmap" {
	declare module.exports: any;
}

// Filename aliases
declare module "@flux-coordinator/heatmapjs/build/heatmap.js" {
	declare module.exports: $Exports<"@flux-coordinator/heatmapjs/build/heatmap">;
}
declare module "@flux-coordinator/heatmapjs/build/heatmap.min.js" {
	declare module.exports: $Exports<
		"@flux-coordinator/heatmapjs/build/heatmap.min"
	>;
}
declare module "@flux-coordinator/heatmapjs/docs/assets/js/prism.js" {
	declare module.exports: $Exports<
		"@flux-coordinator/heatmapjs/docs/assets/js/prism"
	>;
}
declare module "@flux-coordinator/heatmapjs/plugins/angular-heatmap/angular-heatmap.js" {
	declare module.exports: $Exports<
		"@flux-coordinator/heatmapjs/plugins/angular-heatmap/angular-heatmap"
	>;
}
declare module "@flux-coordinator/heatmapjs/plugins/boilerplate.js" {
	declare module.exports: $Exports<
		"@flux-coordinator/heatmapjs/plugins/boilerplate"
	>;
}
declare module "@flux-coordinator/heatmapjs/plugins/gmaps-heatmap/gmaps-heatmap.js" {
	declare module.exports: $Exports<
		"@flux-coordinator/heatmapjs/plugins/gmaps-heatmap/gmaps-heatmap"
	>;
}
declare module "@flux-coordinator/heatmapjs/plugins/leaflet-heatmap/leaflet-heatmap.js" {
	declare module.exports: $Exports<
		"@flux-coordinator/heatmapjs/plugins/leaflet-heatmap/leaflet-heatmap"
	>;
}
declare module "@flux-coordinator/heatmapjs/plugins/segment-heatmap.js" {
	declare module.exports: $Exports<
		"@flux-coordinator/heatmapjs/plugins/segment-heatmap"
	>;
}
declare module "@flux-coordinator/heatmapjs/plugins/svg-area-heatmap.js" {
	declare module.exports: $Exports<
		"@flux-coordinator/heatmapjs/plugins/svg-area-heatmap"
	>;
}
