dist: trusty
language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "flux-coordinator"
    
script:
  - yarn test-ci
  - sonar-scanner