// flow-typed signature: 5aa34d5114421715dc0e9a650b75a4e4
// flow-typed version: <<STUB>>/grommet-addons_v^0.6.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grommet-addons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "grommet-addons" {
	declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "grommet-addons/components/AnnotatedMeter" {
	declare module.exports: any;
}

declare module "grommet-addons/components/FilterControl" {
	declare module.exports: any;
}

declare module "grommet-addons/components/ListPlaceholder" {
	declare module.exports: any;
}

declare module "grommet-addons/components/SideSplit" {
	declare module.exports: any;
}

declare module "grommet-addons/components/Sort" {
	declare module.exports: any;
}

declare module "grommet-addons/grommet-addons.min" {
	declare module.exports: any;
}

declare module "grommet-addons/utils/Query" {
	declare module.exports: any;
}

// Filename aliases
declare module "grommet-addons/components/AnnotatedMeter.js" {
	declare module.exports: $Exports<"grommet-addons/components/AnnotatedMeter">;
}
declare module "grommet-addons/components/FilterControl.js" {
	declare module.exports: $Exports<"grommet-addons/components/FilterControl">;
}
declare module "grommet-addons/components/ListPlaceholder.js" {
	declare module.exports: $Exports<"grommet-addons/components/ListPlaceholder">;
}
declare module "grommet-addons/components/SideSplit.js" {
	declare module.exports: $Exports<"grommet-addons/components/SideSplit">;
}
declare module "grommet-addons/components/Sort.js" {
	declare module.exports: $Exports<"grommet-addons/components/Sort">;
}
declare module "grommet-addons/grommet-addons.min.js" {
	declare module.exports: $Exports<"grommet-addons/grommet-addons.min">;
}
declare module "grommet-addons/index" {
	declare module.exports: $Exports<"grommet-addons">;
}
declare module "grommet-addons/index.js" {
	declare module.exports: $Exports<"grommet-addons">;
}
declare module "grommet-addons/utils/Query.js" {
	declare module.exports: $Exports<"grommet-addons/utils/Query">;
}
