// flow-typed signature: 660ab0599aed52451ee42c36522546e0
// flow-typed version: <<STUB>>/heatmap.js_vgit+https://github.com/Flux-Coordinator/heatmap.js.git/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heatmap.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "heatmap.js" {
	declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "heatmap.js/build/heatmap" {
	declare module.exports: any;
}

declare module "heatmap.js/build/heatmap.min" {
	declare module.exports: any;
}

declare module "heatmap.js/docs/assets/js/prism" {
	declare module.exports: any;
}

declare module "heatmap.js/Gruntfile" {
	declare module.exports: any;
}

declare module "heatmap.js/plugins/angular-heatmap/angular-heatmap" {
	declare module.exports: any;
}

declare module "heatmap.js/plugins/boilerplate" {
	declare module.exports: any;
}

declare module "heatmap.js/plugins/gmaps-heatmap/gmaps-heatmap" {
	declare module.exports: any;
}

declare module "heatmap.js/plugins/leaflet-heatmap/leaflet-heatmap" {
	declare module.exports: any;
}

declare module "heatmap.js/plugins/segment-heatmap" {
	declare module.exports: any;
}

declare module "heatmap.js/plugins/svg-area-heatmap" {
	declare module.exports: any;
}

declare module "heatmap.js/src/config" {
	declare module.exports: any;
}

declare module "heatmap.js/src/core" {
	declare module.exports: any;
}

declare module "heatmap.js/src/data" {
	declare module.exports: any;
}

declare module "heatmap.js/src/renderer" {
	declare module.exports: any;
}

declare module "heatmap.js/src/renderer/canvas-webgl" {
	declare module.exports: any;
}

declare module "heatmap.js/src/renderer/canvas2d" {
	declare module.exports: any;
}

declare module "heatmap.js/src/renderer/vml" {
	declare module.exports: any;
}

declare module "heatmap.js/src/util" {
	declare module.exports: any;
}

declare module "heatmap.js/tests/visual/plugin-modules/gmaps-heatmap" {
	declare module.exports: any;
}

declare module "heatmap.js/tests/visual/plugin-modules/gmaps-node" {
	declare module.exports: any;
}

declare module "heatmap.js/tests/visual/plugin-modules/gmaps-requirejs-main" {
	declare module.exports: any;
}

// Filename aliases
declare module "heatmap.js/build/heatmap.js" {
	declare module.exports: $Exports<"heatmap.js/build/heatmap">;
}
declare module "heatmap.js/build/heatmap.min.js" {
	declare module.exports: $Exports<"heatmap.js/build/heatmap.min">;
}
declare module "heatmap.js/docs/assets/js/prism.js" {
	declare module.exports: $Exports<"heatmap.js/docs/assets/js/prism">;
}
declare module "heatmap.js/Gruntfile.js" {
	declare module.exports: $Exports<"heatmap.js/Gruntfile">;
}
declare module "heatmap.js/plugins/angular-heatmap/angular-heatmap.js" {
	declare module.exports: $Exports<
		"heatmap.js/plugins/angular-heatmap/angular-heatmap"
	>;
}
declare module "heatmap.js/plugins/boilerplate.js" {
	declare module.exports: $Exports<"heatmap.js/plugins/boilerplate">;
}
declare module "heatmap.js/plugins/gmaps-heatmap/gmaps-heatmap.js" {
	declare module.exports: $Exports<
		"heatmap.js/plugins/gmaps-heatmap/gmaps-heatmap"
	>;
}
declare module "heatmap.js/plugins/leaflet-heatmap/leaflet-heatmap.js" {
	declare module.exports: $Exports<
		"heatmap.js/plugins/leaflet-heatmap/leaflet-heatmap"
	>;
}
declare module "heatmap.js/plugins/segment-heatmap.js" {
	declare module.exports: $Exports<"heatmap.js/plugins/segment-heatmap">;
}
declare module "heatmap.js/plugins/svg-area-heatmap.js" {
	declare module.exports: $Exports<"heatmap.js/plugins/svg-area-heatmap">;
}
declare module "heatmap.js/src/config.js" {
	declare module.exports: $Exports<"heatmap.js/src/config">;
}
declare module "heatmap.js/src/core.js" {
	declare module.exports: $Exports<"heatmap.js/src/core">;
}
declare module "heatmap.js/src/data.js" {
	declare module.exports: $Exports<"heatmap.js/src/data">;
}
declare module "heatmap.js/src/renderer.js" {
	declare module.exports: $Exports<"heatmap.js/src/renderer">;
}
declare module "heatmap.js/src/renderer/canvas-webgl.js" {
	declare module.exports: $Exports<"heatmap.js/src/renderer/canvas-webgl">;
}
declare module "heatmap.js/src/renderer/canvas2d.js" {
	declare module.exports: $Exports<"heatmap.js/src/renderer/canvas2d">;
}
declare module "heatmap.js/src/renderer/vml.js" {
	declare module.exports: $Exports<"heatmap.js/src/renderer/vml">;
}
declare module "heatmap.js/src/util.js" {
	declare module.exports: $Exports<"heatmap.js/src/util">;
}
declare module "heatmap.js/tests/visual/plugin-modules/gmaps-heatmap.js" {
	declare module.exports: $Exports<
		"heatmap.js/tests/visual/plugin-modules/gmaps-heatmap"
	>;
}
declare module "heatmap.js/tests/visual/plugin-modules/gmaps-node.js" {
	declare module.exports: $Exports<
		"heatmap.js/tests/visual/plugin-modules/gmaps-node"
	>;
}
declare module "heatmap.js/tests/visual/plugin-modules/gmaps-requirejs-main.js" {
	declare module.exports: $Exports<
		"heatmap.js/tests/visual/plugin-modules/gmaps-requirejs-main"
	>;
}
