// flow-typed signature: 16a92055faf349cbadc3884f21ad8cde
// flow-typed version: <<STUB>>/heatmapjs_vgit+https://github.com/JonathanWi/heatmap.js.git/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heatmapjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "heatmapjs" {
	declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "heatmapjs/build/heatmap" {
	declare module.exports: any;
}

declare module "heatmapjs/build/heatmap.min" {
	declare module.exports: any;
}

declare module "heatmapjs/docs/assets/js/prism" {
	declare module.exports: any;
}

declare module "heatmapjs/Gruntfile" {
	declare module.exports: any;
}

declare module "heatmapjs/plugins/boilerplate" {
	declare module.exports: any;
}

declare module "heatmapjs/plugins/gmaps-heatmap" {
	declare module.exports: any;
}

declare module "heatmapjs/plugins/leaflet-heatmap" {
	declare module.exports: any;
}

declare module "heatmapjs/plugins/segment-heatmap" {
	declare module.exports: any;
}

declare module "heatmapjs/plugins/svg-area-heatmap" {
	declare module.exports: any;
}

declare module "heatmapjs/src/config" {
	declare module.exports: any;
}

declare module "heatmapjs/src/core" {
	declare module.exports: any;
}

declare module "heatmapjs/src/data" {
	declare module.exports: any;
}

declare module "heatmapjs/src/renderer" {
	declare module.exports: any;
}

declare module "heatmapjs/src/renderer/canvas-webgl" {
	declare module.exports: any;
}

declare module "heatmapjs/src/renderer/canvas2d" {
	declare module.exports: any;
}

declare module "heatmapjs/src/renderer/vml" {
	declare module.exports: any;
}

declare module "heatmapjs/src/util" {
	declare module.exports: any;
}

// Filename aliases
declare module "heatmapjs/build/heatmap.js" {
	declare module.exports: $Exports<"heatmapjs/build/heatmap">;
}
declare module "heatmapjs/build/heatmap.min.js" {
	declare module.exports: $Exports<"heatmapjs/build/heatmap.min">;
}
declare module "heatmapjs/docs/assets/js/prism.js" {
	declare module.exports: $Exports<"heatmapjs/docs/assets/js/prism">;
}
declare module "heatmapjs/Gruntfile.js" {
	declare module.exports: $Exports<"heatmapjs/Gruntfile">;
}
declare module "heatmapjs/plugins/boilerplate.js" {
	declare module.exports: $Exports<"heatmapjs/plugins/boilerplate">;
}
declare module "heatmapjs/plugins/gmaps-heatmap.js" {
	declare module.exports: $Exports<"heatmapjs/plugins/gmaps-heatmap">;
}
declare module "heatmapjs/plugins/leaflet-heatmap.js" {
	declare module.exports: $Exports<"heatmapjs/plugins/leaflet-heatmap">;
}
declare module "heatmapjs/plugins/segment-heatmap.js" {
	declare module.exports: $Exports<"heatmapjs/plugins/segment-heatmap">;
}
declare module "heatmapjs/plugins/svg-area-heatmap.js" {
	declare module.exports: $Exports<"heatmapjs/plugins/svg-area-heatmap">;
}
declare module "heatmapjs/src/config.js" {
	declare module.exports: $Exports<"heatmapjs/src/config">;
}
declare module "heatmapjs/src/core.js" {
	declare module.exports: $Exports<"heatmapjs/src/core">;
}
declare module "heatmapjs/src/data.js" {
	declare module.exports: $Exports<"heatmapjs/src/data">;
}
declare module "heatmapjs/src/renderer.js" {
	declare module.exports: $Exports<"heatmapjs/src/renderer">;
}
declare module "heatmapjs/src/renderer/canvas-webgl.js" {
	declare module.exports: $Exports<"heatmapjs/src/renderer/canvas-webgl">;
}
declare module "heatmapjs/src/renderer/canvas2d.js" {
	declare module.exports: $Exports<"heatmapjs/src/renderer/canvas2d">;
}
declare module "heatmapjs/src/renderer/vml.js" {
	declare module.exports: $Exports<"heatmapjs/src/renderer/vml">;
}
declare module "heatmapjs/src/util.js" {
	declare module.exports: $Exports<"heatmapjs/src/util">;
}
