// flow-typed signature: db10b440176330b58b03c795f399196a
// flow-typed version: <<STUB>>/install-peerdeps_v^1.6.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'install-peerdeps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "install-peerdeps" {
	declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "install-peerdeps/lib/cli" {
	declare module.exports: any;
}

declare module "install-peerdeps/lib/constants" {
	declare module.exports: any;
}

declare module "install-peerdeps/lib/helpers" {
	declare module.exports: any;
}

declare module "install-peerdeps/lib/install-peerdeps" {
	declare module.exports: any;
}

declare module "install-peerdeps/src/cli" {
	declare module.exports: any;
}

declare module "install-peerdeps/src/cli.test" {
	declare module.exports: any;
}

declare module "install-peerdeps/src/constants" {
	declare module.exports: any;
}

declare module "install-peerdeps/src/helpers" {
	declare module.exports: any;
}

declare module "install-peerdeps/src/helpers.test" {
	declare module.exports: any;
}

declare module "install-peerdeps/src/install-peerdeps" {
	declare module.exports: any;
}

declare module "install-peerdeps/src/install-peerdeps.test" {
	declare module.exports: any;
}

// Filename aliases
declare module "install-peerdeps/lib/cli.js" {
	declare module.exports: $Exports<"install-peerdeps/lib/cli">;
}
declare module "install-peerdeps/lib/constants.js" {
	declare module.exports: $Exports<"install-peerdeps/lib/constants">;
}
declare module "install-peerdeps/lib/helpers.js" {
	declare module.exports: $Exports<"install-peerdeps/lib/helpers">;
}
declare module "install-peerdeps/lib/install-peerdeps.js" {
	declare module.exports: $Exports<"install-peerdeps/lib/install-peerdeps">;
}
declare module "install-peerdeps/src/cli.js" {
	declare module.exports: $Exports<"install-peerdeps/src/cli">;
}
declare module "install-peerdeps/src/cli.test.js" {
	declare module.exports: $Exports<"install-peerdeps/src/cli.test">;
}
declare module "install-peerdeps/src/constants.js" {
	declare module.exports: $Exports<"install-peerdeps/src/constants">;
}
declare module "install-peerdeps/src/helpers.js" {
	declare module.exports: $Exports<"install-peerdeps/src/helpers">;
}
declare module "install-peerdeps/src/helpers.test.js" {
	declare module.exports: $Exports<"install-peerdeps/src/helpers.test">;
}
declare module "install-peerdeps/src/install-peerdeps.js" {
	declare module.exports: $Exports<"install-peerdeps/src/install-peerdeps">;
}
declare module "install-peerdeps/src/install-peerdeps.test.js" {
	declare module.exports: $Exports<
		"install-peerdeps/src/install-peerdeps.test"
	>;
}
